export const MOCK_DASHBOARD_DATA = {
  tickers: [
    { symbol: "SPY", price: "567.43", change: 0.82 },
    { symbol: "QQQ", price: "478.21", change: 1.14 },
    { symbol: "BTC", price: "84,250", change: 2.31 },
    { symbol: "ETH", price: "3,182", change: 1.87 },
    { symbol: "AAPL", price: "213.49", change: 0.54 },
    { symbol: "TSLA", price: "271.32", change: -1.23 },
    { symbol: "NVDA", price: "875.60", change: 3.12 },
    { symbol: "GOLD", price: "3,021", change: 0.41 },
    { symbol: "DXY", price: "103.82", change: -0.18 },
    { symbol: "VIX", price: "17.43", change: -2.10 },
  ],
  assets: [
    { name: "S&P 500", symbol: "SPX", value: "5,674", change_1d: 0.82, change_1w: 1.94, sparkline: [45, 48, 44, 50, 52, 49, 55, 58] },
    { name: "Nasdaq", symbol: "NDX", value: "19,842", change_1d: 1.14, change_1w: 2.43, sparkline: [40, 45, 42, 48, 52, 50, 56, 60] },
    { name: "Bitcoin", symbol: "BTC", value: "$84,250", change_1d: 2.31, change_1w: 5.12, sparkline: [55, 52, 60, 58, 62, 65, 63, 70] },
    { name: "Gold", symbol: "XAU", value: "$3,021", change_1d: 0.41, change_1w: 1.20, sparkline: [60, 62, 61, 63, 64, 62, 65, 66] },
    { name: "DXY", symbol: "DXY", value: "103.82", change_1d: -0.18, change_1w: -0.72, sparkline: [52, 51, 53, 50, 49, 51, 48, 47] },
    { name: "WTI Oil", symbol: "WTI", value: "$78.42", change_1d: -0.63, change_1w: -1.40, sparkline: [60, 58, 57, 59, 56, 55, 54, 53] },
    { name: "10Y Yield", symbol: "TNX", value: "4.31%", change_1d: 0.02, change_1w: 0.08, sparkline: [44, 46, 45, 47, 46, 48, 47, 49] },
    { name: "VIX", symbol: "VIX", value: "17.43", change_1d: -2.10, change_1w: -4.30, sparkline: [65, 60, 58, 55, 52, 50, 48, 45] },
  ],
  fear_greed: {
    value: 62,
    label: "Greed",
    vix: 17.43,
    summary: "El mercado muestra apetito por el riesgo moderado. Los inversores están comprando activos de riesgo, aunque la volatilidad sigue controlada.",
  },
  gainers: [
    { symbol: "NVDA", name: "NVIDIA Corp", price: "$875.60", change_pct: 3.12 },
    { symbol: "META", name: "Meta Platforms", price: "$512.30", change_pct: 2.87 },
    { symbol: "BTC", name: "Bitcoin", price: "$84,250", change_pct: 2.31 },
    { symbol: "AMD", name: "Advanced Micro", price: "$168.42", change_pct: 1.94 },
    { symbol: "AMZN", name: "Amazon", price: "$198.76", change_pct: 1.52 },
  ],
  losers: [
    { symbol: "TSLA", name: "Tesla Inc", price: "$271.32", change_pct: -1.23 },
    { symbol: "WTI", name: "WTI Crude Oil", price: "$78.42", change_pct: -0.63 },
    { symbol: "JPM", name: "JPMorgan Chase", price: "$198.10", change_pct: -0.54 },
    { symbol: "DXY", name: "US Dollar Index", price: "103.82", change_pct: -0.18 },
    { symbol: "GS", name: "Goldman Sachs", price: "$481.20", change_pct: -0.12 },
  ],
  headlines: [
    {
      title: "Fed mantiene tasas sin cambios, señala posibles recortes en el segundo semestre",
      summary: "La Reserva Federal decidió mantener las tasas de interés en el rango 5.25%-5.50%, citando progreso en inflación pero señalando necesidad de más datos.",
      sentiment: "positive",
      source: "Reuters",
      time_ago: "hace 2h",
    },
    {
      title: "NVIDIA supera expectativas con ingresos récord en chips de IA",
      summary: "NVIDIA reportó ingresos de $22.1B en el trimestre, superando estimaciones por un 12%. La demanda de chips H100 sigue siendo masiva.",
      sentiment: "positive",
      source: "Bloomberg",
      time_ago: "hace 4h",
    },
    {
      title: "Bitcoin consolida por encima de $84K tras semanas de volatilidad",
      summary: "El precio de Bitcoin se mantiene estable cerca de máximos, con el mercado anticipando el próximo halving y posibles ETFs adicionales.",
      sentiment: "positive",
      source: "CoinDesk",
      time_ago: "hace 5h",
    },
    {
      title: "Tesla enfrenta presión competitiva creciente en China",
      summary: "BYD y otros fabricantes chinos continúan ganando participación de mercado, presionando los márgenes de Tesla en la región.",
      sentiment: "negative",
      source: "WSJ",
      time_ago: "hace 6h",
    },
    {
      title: "Oro alcanza nuevos máximos históricos superando los $3,000 por onza",
      summary: "El metal dorado continúa su rally impulsado por compras de bancos centrales y demanda como refugio ante incertidumbre geopolítica.",
      sentiment: "positive",
      source: "FT",
      time_ago: "hace 8h",
    },
  ],
  signals: [
    { symbol: "NVDA", name: "NVIDIA", asset_type: "stock", action: "BUY", price: "$875", target: "$950", stop: "$830", strength: 88, reason: "Ruptura de resistencia clave con volumen institucional elevado. IA boom continúa.", timeframe: "2-4 semanas", pattern: "Bull Flag" },
    { symbol: "BTC", name: "Bitcoin", asset_type: "crypto", action: "BUY", price: "$84,250", target: "$92,000", stop: "$78,000", strength: 75, reason: "Consolidación alcista sobre soporte clave. Momentum positivo pre-halving.", timeframe: "1-3 semanas", pattern: "Ascending Triangle" },
    { symbol: "TSLA", name: "Tesla", asset_type: "stock", action: "WATCH", price: "$271", target: "$290", stop: "$255", strength: 52, reason: "Zona de soporte importante. Esperar confirmación de rebote antes de entrar.", timeframe: "1-2 semanas", pattern: "Support Test" },
    { symbol: "GLD", name: "Gold ETF", asset_type: "etf", action: "BUY", price: "$192", target: "$205", stop: "$186", strength: 82, reason: "Tendencia alcista sólida, bancos centrales comprando agresivamente.", timeframe: "1-2 meses", pattern: "Breakout" },
    { symbol: "QQQ", name: "Nasdaq ETF", asset_type: "etf", action: "BUY", price: "$478", target: "$510", stop: "$458", strength: 70, reason: "Sector tecnológico liderando el mercado. RSI en zona neutral con momentum.", timeframe: "3-6 semanas", pattern: "Trend Continuation" },
    { symbol: "META", name: "Meta Platforms", asset_type: "stock", action: "BUY", price: "$512", target: "$560", stop: "$488", strength: 79, reason: "Fuerte crecimiento en IA y monetización. Múltiplos razonables para el sector.", timeframe: "2-4 semanas", pattern: "Cup & Handle" },
    { symbol: "DXY", name: "US Dollar", asset_type: "forex", action: "SELL", price: "103.82", target: "101.50", stop: "105.00", strength: 65, reason: "Debilidad del dólar esperada si Fed confirma recortes. Presión bajista técnica.", timeframe: "2-3 semanas", pattern: "Descending Channel" },
    { symbol: "WTI", name: "Crude Oil", asset_type: "etf", action: "WATCH", price: "$78.42", target: "$82.00", stop: "$74.00", strength: 48, reason: "Zona de soporte clave. Datos de inventarios de EIA esta semana serán determinantes.", timeframe: "1-2 semanas", pattern: "Range Bound" },
  ],
  market_bias: "Sesión EE.UU. · Sesgo alcista moderado",
  session: "Mercados abiertos · Sesgo alcista moderado",
};