import { useState, useEffect } from "react";
import { buildPatternData } from '@/services/panelDataService';

export default function ChartPatterns({ symbol }) {
  const [data, setData] = useState(null);
  useEffect(() => { if (!symbol) return; buildPatternData(symbol).then(setData); }, [symbol]);
  if (!symbol || !data) return null;
  return <div className="space-y-4">{data.active_patterns?.map((p) => <div key={p.name} className="rounded-xl border border-border bg-secondary/20 p-4"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold text-foreground">{p.name}</p><p className="text-[10px] text-muted-foreground mt-0.5">{p.status}</p></div><div className="text-right"><span className="text-xs font-bold text-primary">{p.reliability}%</span></div></div><p className="text-xs text-muted-foreground my-2">{p.explanation}</p><div className="grid grid-cols-2 gap-2"><div className="rounded-lg bg-green-500/10 border border-green-500/20 px-2 py-1"><p className="text-[9px] text-muted-foreground">Target</p><p className="text-xs font-bold text-green-400">{p.target}</p></div><div className="rounded-lg bg-red-500/10 border border-red-500/20 px-2 py-1"><p className="text-[9px] text-muted-foreground">Stop Loss</p><p className="text-xs font-bold text-red-400">{p.stop_loss}</p></div></div></div>)}{data.candlestick_patterns?.map((p) => <div key={p.name} className="rounded-xl border border-border bg-secondary/20 p-3"><p className="text-xs font-semibold text-foreground">{p.name}</p><p className="text-[10px] text-muted-foreground mt-1">{p.explanation}</p></div>)}{data.elliott_wave && <div className="rounded-xl border border-border bg-secondary/20 p-4"><p className="text-[10px] text-muted-foreground uppercase tracking-wider mb-1">Elliott Wave</p><p className="text-sm text-foreground">{data.elliott_wave}</p></div>}</div>;
}
