import { useState, useEffect } from "react";
import { Globe } from "lucide-react";
import { buildMacroData } from '@/services/panelDataService';

export default function MacroPanel({ symbol }) {
  const [data, setData] = useState(null);
  useEffect(() => { if (!symbol) return; buildMacroData(symbol).then(setData); }, [symbol]);
  if (!symbol || !data) return null;
  const macroItems = [{ label: 'DXY', item: data.dxy }, { label: 'VIX', item: data.vix }, { label: '10Y Yield', item: data.yield_10y }, { label: 'WTI Oil', item: data.oil }, { label: 'Gold', item: data.gold }];
  const riskPct = ((data.risk_score + 100) / 200) * 100;
  return <div className="space-y-4"><div className="rounded-xl border border-green-500/30 bg-green-500/5 p-4"><div className="flex items-center justify-between mb-3"><div className="flex items-center gap-2"><Globe className="h-4 w-4 text-muted-foreground" /><span className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">Ambiente Macro</span></div><span className="text-sm font-bold text-green-400">{data.macro_signal?.toUpperCase()}</span></div><div className="h-3 bg-secondary rounded-full overflow-hidden relative"><div className="absolute inset-0 bg-gradient-to-r from-red-500 via-yellow-500 to-green-500 opacity-30 rounded-full" /><div className="absolute top-0.5 bottom-0.5 w-3 rounded-full bg-white shadow-lg transition-all duration-1000" style={{ left: `calc(${riskPct}% - 6px)` }} /></div><p className="text-xs text-muted-foreground mt-3">{data.macro_summary}</p></div><div className="grid grid-cols-1 gap-2">{macroItems.map(({ label, item }) => <div key={label} className="rounded-xl border border-border bg-secondary/20 p-3"><div className="flex items-center justify-between"><div><p className="text-[10px] text-muted-foreground">{label}</p><p className="text-sm font-bold text-foreground">{item.value}</p></div><div className="text-right"><p className="text-xs text-muted-foreground">{item.trend}</p><p className="text-xs text-foreground">{item.impact}</p></div></div></div>)}</div><div className="rounded-xl border border-border bg-secondary/20 p-3"><p className="text-[10px] text-muted-foreground uppercase tracking-wider mb-1">Fed / Banco Central</p><p className="text-xs text-foreground">{data.fed_stance}</p></div><div className="rounded-xl border border-border bg-secondary/20 p-3"><p className="text-[10px] text-muted-foreground uppercase tracking-wider mb-1">Rotación Sectorial</p><p className="text-xs text-foreground">{data.sector_rotation}</p></div></div>;
}
