import { useState } from "react";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Search, Loader2 } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import { analyzeAsset } from '@/services/marketDataService';
import { db } from '@/api/localClient';

const signalConfig = { strong_buy: { label: "COMPRA FUERTE", color: "text-green-400", bg: "bg-green-500/10", border: "border-green-500/30" }, buy: { label: "COMPRA", color: "text-green-400", bg: "bg-green-500/10", border: "border-green-500/30" }, hold: { label: "MANTENER", color: "text-yellow-400", bg: "bg-yellow-500/10", border: "border-yellow-500/30" }, sell: { label: "VENTA", color: "text-red-400", bg: "bg-red-500/10", border: "border-red-500/30" }, strong_sell: { label: "VENTA FUERTE", color: "text-red-400", bg: "bg-red-500/10", border: "border-red-500/30" } };

export default function QuickAnalysis() {
  const [symbol, setSymbol] = useState(""); const [loading, setLoading] = useState(false); const [result, setResult] = useState(null);
  const analyze = async () => { if (!symbol.trim()) return; setLoading(true); const data = await analyzeAsset(symbol.toUpperCase()); setResult(data); await db.entities.AnalysisHistory.create({ symbol: data.symbol, asset_type: data.asset_type || 'stock', analysis_data: JSON.stringify(data), signal: data.signal || 'hold', score: data.score || 50 }); setLoading(false); };
  const sig = result ? signalConfig[result.signal] || signalConfig.hold : null;
  return <div className="rounded-2xl border border-border bg-card/50 p-6"><h2 className="text-lg font-semibold text-foreground mb-4">Análisis Rápido</h2><div className="flex gap-2 mb-6"><Input placeholder="Ingresa un ticker (AAPL, BTC-USD, TSLA...)" value={symbol} onChange={(e) => setSymbol(e.target.value.toUpperCase())} onKeyDown={(e) => e.key === "Enter" && analyze()} className="bg-secondary border-border text-foreground placeholder:text-muted-foreground" /><Button onClick={analyze} disabled={loading} className="bg-primary text-primary-foreground hover:bg-primary/90 px-6">{loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Search className="h-4 w-4" />}</Button></div><AnimatePresence>{result && sig && <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} className="space-y-4"><div className={`rounded-xl ${sig.bg} border ${sig.border} p-5`}><div className="flex items-center justify-between mb-3"><div><h3 className="text-xl font-bold text-foreground">{result.symbol}</h3><p className="text-sm text-muted-foreground">{result.name}</p></div><div className="text-right"><p className="text-2xl font-bold text-foreground">{result.current_price}</p><p className={`text-sm font-medium ${result.daily_change_pct >= 0 ? "text-green-400" : "text-red-400"}`}>{result.daily_change_pct >= 0 ? "+" : ""}{result.daily_change_pct?.toFixed(2)}%</p></div></div><div className="flex items-center gap-3"><span className={`text-lg font-bold ${sig.color}`}>{sig.label}</span><div className="flex-1 h-2 rounded-full bg-secondary overflow-hidden"><div className="h-full rounded-full bg-primary transition-all duration-1000" style={{ width: `${result.score}%` }} /></div><span className="text-sm font-bold text-foreground">{result.score}/100</span></div></div><div className="rounded-xl bg-secondary/30 border border-border p-4"><p className="text-sm text-foreground leading-relaxed">{result.summary}</p></div></motion.div>}</AnimatePresence></div>;
}
